import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Next-Hero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-red-500">
          <ul className="flex justify-center items-center gap-5">
            <li>Home</li>
            <li>About</li>
            <li>Contact</li>
            <li>News</li>
            <li>Blog</li>
            <li>Login</li>
          </ul>
        </nav>
        <div className="h-screen">
        {children}
        </div>
        <footer className="flex justify-center">
          This Is Footer Part
        </footer>
      </body>
    </html>
  );
}
